### ISSUE TITLE
FOSS flavour

### ISSUE THREAD

**Issue by fossdd** [TigerBeanst/RnIntentClean#7]
RnIntentClean currently requires properitary GMS Services, Crashlytics, firebase and other things.

Would great if you can enstablish a Open Source Flavour that uses Open Source Dependencies, like [ACRA](https://github.com/ACRA/acra) as Crashlytics replacement.

With prop. dependencies we at the [F-Droid Store](https://f-droid.org) are unable to package your app.

**Comment by TigerBeanst** [comment]
At this time, RnIntentClean will not consider supporting FOSS. On the one hand, Firebase does a good job of parsing and crash statistics. On the other hand, due to its auto-packaging feature, it was easy to package my (JUNK) code I was pushing into an APK and it may not work properly.

**Comment by fossdd** [comment]
Oh. Okay. Just notice that Firebase, Crashlytics, co. are services by Google which collect data for their self. Only Google can view the source code. Looks that you entered the Google door and you can't leave... 😞 

F-Droid want to reach a FOSS Store with only Non-Google-Apps for the whole world. Every app source is visible and dependencies..
